# Configuración del Torneo de Magos
# Cantidad de magos participantes
magos.count=3

# Información de cada mago
magos.0.nombre=Harry Potter
magos.0.casa=Gryffindor

magos.1.nombre=Draco Malfoy
magos.1.casa=Slytherin

magos.2.nombre=Hermione Granger
magos.2.casa=Gryffindor

# Cantidad de hechizos disponibles
hechizos.count=5

# Información de cada hechizo
hechizos.0.nombre=Expelliarmus
hechizos.0.poder=45

hechizos.1.nombre=Petrificus Totalus
hechizos.1.poder=35

hechizos.2.nombre=Stupefy
hechizos.2.poder=40

hechizos.3.nombre=Protego
hechizos.3.poder=30

hechizos.4.nombre=Avada Kedavra
hechizos.4.poder=100

